Molecules/Cardの作成
yusukekosaka358/yusuke-kosaka-frontend-basic-last-assignment pull request #4
Opened 2022-07-10 09:06 UTC by yusukekosaka358

## セルフチェック
- [o] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [o] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [o] 記述の重複はないか

リンク
[https://62922db46eca29004a7a378d-lejcshbuee.chromatic.com/?path=/story/atoms-button--button](chromatic上の該当ページへのリンクを貼る)

2022-07-11 04:05 UTC, KEISUKE0293 reviewed
- cardの外枠が丸くなっているので直してください！
- 画像の幅が固定されているのでcardの幅に合わせて変わるようにして下さい！（どちらかというとhtmlの構造が問題な気がします、）
- hover解除後もゆっくり大きさが戻るようにしてください！

では、修正お願いします！

2022-07-11 04:05 UTC, KEISUKE0293 commented on src/components/molecules/card/card.html
> +    <div class="card-title">
ここの文字の色が違います！

2022-07-22 10:49 UTC, yusukekosaka358 commented
質問です。なぜ指定していないのに外枠が丸くなってしまったのでしょうか？
あともう一つ、HTMLで現在.card-imageの中に画像を入れているのですが、そうしたことで画像の大きさが固定されてしまいました。しかし.card-imageという要素がないと画像を拡大したときに画像がはみ出てしまうのですがどうすればいいですか？

2022-07-28 09:54 UTC, higashiji2000 commented
> なぜ指定していないのに外枠が丸くなってしまったのでしょうか？

これは `.card` というクラス名を付けたことによってbootstrapのCardsコンポーネントのスタイルが反映されてしまったことによるものです。
https://getbootstrap.jp/docs/5.0/components/card/

---

> HTMLで現在.card-imageの中に画像を入れているのですが、そうしたことで画像の大きさが固定されてしまいました。しかし.card-imageという要素がないと画像を拡大したときに画像がはみ出てしまうのですがどうすればいいですか？

画像の大きさが固定された
 -> img 要素の標準の挙動  

.card-image で囲まない場合幅いっぱいに広がる  
-> `.card` がbootstrap側のスタイルシートでflexboxになっている
-> かつ flex-direction が column になっている
flexboxのalig n-itemsプロパティはデフォルトでnormal となっており、これは stretch とだいたい同じです。
align-items の効力で、columnの交差軸方向である横方向に子要素が引き延ばされることにより、画像が横幅いっぱいに広がっていたということです。
flexの挙動は複雑なので、一度詳しく調べてみることをおススメします。
https://developer.mozilla.org/ja/docs/Web/CSS/align-items

どうすればいいか
-> 画像に対し `width: 100%` を指定する
これが一番簡単な気がします。


下の画像は `img` を `.card` 直下に配置したうえで、`.card` の `display: flex` を無効化したときの表示です。
flex じゃないと横幅いっぱいに広がらないことがわかると思います。
![image](https://user-images.githubusercontent.com/83479175/181474956-a8aaf09e-62af-44c6-a073-8d8b45eb2376.png)

2022-08-08 05:07 UTC, haruchu reviewed
コメントしました

2022-08-08 05:07 UTC, haruchu commented on src/components/molecules/card/card.scss
> +                transition: all 0.5s ease;
ここに指定してしまうと、hover時のみに適応され、hoverを外した時には適応されません

2022-08-08 05:07 UTC, haruchu commented on src/components/molecules/card/card.scss
> +    .triangle {
こちら`.card-title`の疑似要素にすると記載少し減るかと思います

2022-08-08 05:07 UTC, haruchu commented on src/components/molecules/card/card.scss
> +            &:hover {
figmaにもあるように画面幅がs以下の時は拡大しなくて良いです
<img width="306" alt="スクリーンショット 2022-08-08 14 05 48" src="https://user-images.githubusercontent.com/66406382/183343244-06dbad94-2177-4067-99d8-0875ba193ae2.png">

2022-08-08 05:07 UTC, haruchu commented on src/components/molecules/card/card.html
> +    <p class="card-text">
文字多い時横に余白が欲しいです
<img width="506" alt="スクリーンショット 2022-08-08 14 06 47" src="https://user-images.githubusercontent.com/66406382/183343355-4c3e22c0-a03f-4c3c-be3f-9354f631364b.png">

2022-08-09 07:16 UTC, yusukekosaka358 commented
.triangleを.card-titleの擬似要素にした方がよいとご指摘いただきましたがどのようにするかわかりません。調べてみて::afterを使うのかなと思ったのですが三角が消えてしまいます（みえない）。擬似要素は::afterでいいのか、また違うなら何を使えばいいのか教えていただきたいです。

2022-08-09 07:16 UTC, yusukekosaka358 commented
![スクリーンショット 2022-08-09 161340](https://user-images.githubusercontent.com/105427908/183587959-3078320f-d92e-4951-963b-b2b813072572.jpg)

2022-08-09 07:32 UTC, haruchu commented
> ![スクリーンショット 2022-08-09 161340](https://user-images.githubusercontent.com/105427908/183587959-3078320f-d92e-4951-963b-b2b813072572.jpg)

参考にしてみてください
https://qiita.com/7note/items/7cb88dca241a22b54e5c

2022-08-12 12:03 UTC, higashiji2000 requested changes
![image](https://user-images.githubusercontent.com/83479175/184348518-7a10b7af-fd3d-42b4-b2e5-f05d9050fb4f.png)
下の部分に背景色がついているので、再現をお願いします。

また、figmaの方にはborderがついていないので、こちらも修正お願いします。
![image](https://user-images.githubusercontent.com/83479175/184350107-b37cdba1-7594-4a75-965f-3e8bb959ec5f.png)

![image](https://user-images.githubusercontent.com/83479175/184350168-3ea990cf-1db2-4d58-9ff2-d81929c2e80d.png)

2022-08-12 12:03 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +            left: -6px;
titleのbefore疑似要素ではなく、.card等の疑似要素とすればleftで打ち消しあう必要性がなくなる気がします（今回は見た目が合っているのでOKです）

2022-08-12 12:03 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +    }
それぞれにmarginを設定するのではなく、figmaでいう card-body 要素にpaddingを設定すると余白の指定が分散せずいい感じかと思います。
https://www.figma.com/file/itngQHR9R5RB7xwCXAKOde/TCD-Theme?node-id=807%3A1846

2022-08-12 12:03 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +            }
このあたりインデントがずれているので、prettierが効いているかどうか確認お願いします 🙇

2022-08-26 07:48 UTC, yusukekosaka358 commented on src/components/molecules/card/card.scss
> +            }
今まで機能していなかったみたいです。ご指摘ありがとうございます！

2022-08-26 08:10 UTC, yusukekosaka358 commented
一つ質問です。今回直したborderが勝手にあったのもbootstrapのCardsコンポーネントのスタイルが反映されてしまっていたのが原因でしょうか？またこのcssは<div class="card">の名前を変えれば記述量が減ると思うのですが変えた方が良いですか？

2022-08-27 06:10 UTC, higashiji2000 approved these changes
> 一つ質問です。今回直したborderが勝手にあったのもbootstrapのCardsコンポーネントのスタイルが反映されてしまっていたのが原因でしょうか？またこのcssは
の名前を変えれば記述量が減ると思うのですが変えた方が良いですか？

大事なところが消えてしまっていますが、現状問題ないのでapproveのみしておきます。
変えたいと思ったらもう一度レビュー依頼を出していただくようお願いします！
問題なければマージしてしまってOKです 🙆‍♂️

2022-08-27 06:10 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +      text-align: center;
これは button.scss にも書いてあるのでなくても問題なさそうですね！
![image](https://user-images.githubusercontent.com/83479175/187016835-3eb95f3d-f2a9-4724-bde4-ea8059da0e00.png)

2022-08-27 06:10 UTC, Higashiji commented on src/components/molecules/card/card.scss
> +      transition: all 0.5s ease;
今回のように効いてほしいプロパティが限定されている場合は、このように書くと思わぬ副作用が出づらいのでお勧めです。
```suggestion
      transition: transform 0.5s ease;
```

2022-08-27 06:10 UTC, higashiji2000 commented on src/components/molecules/card/card.scss
> +      @media screen and (min-width: $breakpoint-md) {
message や button だと max-width で作成していたので、基本的に統一したいです。
今回は作成済みなので大丈夫ですが、以後max-width のデスクトップファーストで記述するようお願いします！

2022-08-27 08:22 UTC, merged